// lib/bulas.js — Base de dados de bulas estruturadas
export const BULAS = [
  {
    slug: 'dipirona-sodica-500mg',
    nome: 'Dipirona Sódica 500mg',
    principio_ativo: 'Dipirona Sódica (Metamizol Sódico)',
    categoria: 'Analgésico e Antitérmico',
    classe: 'Analgésico não opioide',
    receita: false,
    tarja: 'Sem tarja',
    formas: ['Comprimido', 'Gotas', 'Solução injetável', 'Supositório'],
    laboratorios: ['Medley', 'EMS', 'Neo Química', 'Sanofi', 'Farmasa'],
    registro_anvisa: true,
    indicacoes: 'A Dipirona Sódica é indicada para o tratamento de dores agudas de moderada a forte intensidade, como cólicas renais e biliares, dores pós-operatórias, dores causadas por tumores, bem como febre resistente a outras medidas terapêuticas.',
    contraindicacoes: 'Contraindicado para pacientes com hipersensibilidade à dipirona ou outras pirazolonas, porfiria hepática aguda, deficiência congênita de glicose-6-fosfato-desidrogenase, grávidas no primeiro trimestre e últimas 6 semanas de gestação, lactantes, crianças com menos de 3 meses ou com peso inferior a 5kg.',
    posologia: {
      adultos: 'A dose habitual para adultos é de 500mg a 1g (1 a 2 comprimidos de 500mg), podendo ser repetida a cada 6 a 8 horas, não excedendo 4g por dia.',
      criancas: 'Para crianças, a dose é calculada pelo peso: 10 a 20mg/kg por dose, a cada 6 a 8 horas conforme necessidade.',
      idosos: 'Em idosos, recomenda-se cautela e doses menores devido ao maior risco de efeitos adversos renais.',
    },
    composicao: 'Cada comprimido contém: Dipirona Sódica monoidratada 500mg. Excipientes: celulose microcristalina, amido, estearato de magnésio, talco, dióxido de silício.',
    mecanismo_acao: 'A dipirona age inibindo a síntese de prostaglandinas no sistema nervoso central, reduzindo a transmissão de impulsos dolorosos e a regulação da temperatura corporal no hipotálamo.',
    efeitos_adversos: ['Reações alérgicas (urticária, edema)', 'Agranulocitose (raro mas grave)', 'Hipotensão (especialmente via injetável)', 'Náuseas', 'Irritação gástrica'],
    interacoes: ['Anticoagulantes orais: pode potencializar o efeito', 'Ciclosporina: pode reduzir os níveis séricos', 'Cloranfenicol: pode aumentar a meia-vida', 'Álcool: pode potencializar os efeitos sedativos'],
    conservacao: 'Conservar em temperatura ambiente (15°C a 30°C), protegido da luz e umidade. Manter fora do alcance de crianças.',
    superdosagem: 'Em casos de superdosagem, podem ocorrer náuseas, vômitos, dor abdominal, insuficiência renal e hepática. Procure atendimento médico imediatamente.',
    gravidez: 'Categoria C. Contraindicado no primeiro trimestre e nas últimas 6 semanas de gestação.',
    faq: [
      { q: 'Dipirona serve para dor de cabeça?', a: 'Sim, a Dipirona é eficaz para dores de cabeça e enxaqueca leve a moderada.' },
      { q: 'Posso tomar Dipirona com estômago vazio?', a: 'Sim, a Dipirona pode ser tomada com ou sem alimentos, mas tomar com alimentos pode reduzir a irritação gástrica.' },
      { q: 'Qual a diferença entre Dipirona e Paracetamol?', a: 'Ambos são analgésicos e antitérmicos, mas a Dipirona tem ação mais intensa para cólicas e dores agudas, enquanto o Paracetamol é mais suave e indicado para crianças menores.' },
      { q: 'Dipirona 500mg pode ser partido ao meio?', a: 'Sim, comprimidos de Dipirona 500mg podem ser partidos ao meio para doses menores, desde que não sejam comprimidos de liberação prolongada.' },
    ],
  },
  {
    slug: 'omeprazol-20mg',
    nome: 'Omeprazol 20mg',
    principio_ativo: 'Omeprazol',
    categoria: 'Antiácido',
    classe: 'Inibidor de Bomba de Prótons (IBP)',
    receita: false,
    tarja: 'Tarja vermelha',
    formas: ['Cápsula', 'Comprimido gastrorresistente'],
    laboratorios: ['EMS', 'Neo Química', 'Medley', 'Eurofarma', 'AstraZeneca (Losec)'],
    registro_anvisa: true,
    indicacoes: 'O Omeprazol é indicado para tratamento de úlcera gástrica e duodenal, doença do refluxo gastroesofágico (DRGE), síndrome de Zollinger-Ellison, erradicação do H. pylori e prevenção de lesões gastroduodenais por AINEs.',
    contraindicacoes: 'Contraindicado para pacientes com hipersensibilidade ao omeprazol, outros IBPs ou qualquer componente da fórmula. Usar com cautela em pacientes com doença hepática grave.',
    posologia: {
      adultos: 'Para refluxo e gastrite: 20mg uma vez ao dia, preferencialmente em jejum, 30 a 60 minutos antes do café da manhã. Para úlcera: 20 a 40mg uma vez ao dia por 4 a 8 semanas.',
      criancas: 'Para crianças acima de 2 anos: 0,7 a 3,3mg/kg/dia, conforme prescrição médica.',
      idosos: 'Não é necessário ajuste de dose em idosos.',
    },
    composicao: 'Cada cápsula contém: Omeprazol 20mg. Excipientes: manitol, crospovidona, eudragit, laurilsulfato de sódio, sacarose.',
    mecanismo_acao: 'O Omeprazol inibe de forma irreversível a enzima H+/K+-ATPase (bomba de prótons) nas células parietais do estômago, reduzindo a produção de ácido gástrico de forma potente e prolongada.',
    efeitos_adversos: ['Dor de cabeça', 'Diarreia', 'Náusea', 'Flatulência', 'Deficiência de magnésio (uso prolongado)', 'Maior risco de infecções intestinais (uso prolongado)'],
    interacoes: ['Clopidogrel: reduz o efeito anticoagulante', 'Metotrexato: aumenta toxicidade', 'Cetoconazol e itraconazol: absorção reduzida', 'Vitamina B12: absorção reduzida no uso prolongado'],
    conservacao: 'Conservar em temperatura abaixo de 25°C, protegido da luz e umidade. Não refrigerar.',
    superdosagem: 'Doses até 160mg foram bem toleradas. Em superdosagem, pode haver confusão, sonolência, visão turva. Busque atendimento médico.',
    gravidez: 'Categoria C. Usar somente se claramente necessário, sob orientação médica.',
    faq: [
      { q: 'Omeprazol pode ser tomado junto com outros remédios?', a: 'O Omeprazol pode interagir com vários medicamentos. Sempre informe seu médico ou farmacêutico sobre todos os medicamentos que você toma.' },
      { q: 'Por quanto tempo posso tomar Omeprazol?', a: 'O tempo de uso depende da indicação. Para refluxo leve: 4 semanas. Para úlceras: até 8 semanas. Uso prolongado requer acompanhamento médico.' },
      { q: 'Omeprazol deve ser tomado antes ou depois do café?', a: 'O Omeprazol deve ser tomado 30 a 60 minutos ANTES do café da manhã, em jejum, para máxima eficácia.' },
      { q: 'Posso tomar Omeprazol todo dia?', a: 'O uso diário por longos períodos pode causar deficiência de magnésio e vitamina B12. Siga sempre a orientação médica.' },
    ],
  },
  {
    slug: 'amoxicilina-500mg',
    nome: 'Amoxicilina 500mg',
    principio_ativo: 'Amoxicilina tri-hidratada',
    categoria: 'Antibiótico',
    classe: 'Penicilina semissintética',
    receita: true,
    tarja: 'Tarja vermelha',
    formas: ['Cápsula', 'Comprimido', 'Suspensão oral', 'Pó para suspensão'],
    laboratorios: ['EMS', 'Neo Química', 'Medley', 'Teuto', 'GlaxoSmithKline (Amoxil)'],
    registro_anvisa: true,
    indicacoes: 'A Amoxicilina é indicada para infecções causadas por bactérias sensíveis à amoxicilina, incluindo infecções do trato respiratório superior e inferior, infecções do trato urinário, infecções da pele e tecidos moles, infecções dentárias e profilaxia de endocardite bacteriana.',
    contraindicacoes: 'Contraindicado em pacientes com hipersensibilidade às penicilinas, cefalosporinas ou outros alérgenos beta-lactâmicos. Histórico de reação alérgica grave (anafilaxia) à penicilina.',
    posologia: {
      adultos: 'Para infecções leves a moderadas: 500mg a cada 8 horas ou 875mg a cada 12 horas. Para infecções graves: 500mg a cada 6 horas. Duração: geralmente 7 a 10 dias.',
      criancas: 'Para crianças: 25 a 50mg/kg/dia divididos em doses a cada 8 horas, conforme peso e gravidade da infecção.',
      idosos: 'Não é necessário ajuste de dose em idosos com função renal normal.',
    },
    composicao: 'Cada cápsula contém: Amoxicilina tri-hidratada equivalente a 500mg de amoxicilina. Excipientes: estearato de magnésio, dióxido de silício coloidal.',
    mecanismo_acao: 'A Amoxicilina age inibindo a síntese da parede celular bacteriana, ligando-se às proteínas de ligação à penicilina (PBPs), levando à lise e morte das bactérias.',
    efeitos_adversos: ['Diarreia', 'Náusea e vômito', 'Erupção cutânea', 'Reações alérgicas', 'Candidíase oral ou vaginal', 'Colite pseudomembranosa (raro)'],
    interacoes: ['Anticoagulantes orais: pode potencializar o efeito', 'Metotrexato: aumenta toxicidade', 'Probenecida: aumenta níveis séricos da amoxicilina', 'Contraceptivos orais: pode reduzir a eficácia'],
    conservacao: 'Cápsulas: temperatura ambiente (até 30°C). Suspensão reconstituída: refrigerar entre 2°C e 8°C, usar em até 7 dias.',
    superdosagem: 'Em caso de superdosagem, pode ocorrer diarreia, náusea, vômito e distúrbios do equilíbrio eletrolítico. Procure atendimento médico.',
    gravidez: 'Categoria B. Pode ser usado durante a gravidez quando necessário, sob orientação médica.',
    faq: [
      { q: 'Posso tomar Amoxicilina sem receita?', a: 'Não. A Amoxicilina é um antibiótico que requer receita médica. O uso sem prescrição pode contribuir para resistência bacteriana.' },
      { q: 'O que acontece se eu parar de tomar Amoxicilina antes do prazo?', a: 'Interromper o antibiótico antes do fim do tratamento pode fazer com que as bactérias sobrevivam e se tornem resistentes, além de causar recidiva da infecção.' },
      { q: 'Amoxicilina serve para gripe?', a: 'Não. Gripe é causada por vírus, e antibióticos como a Amoxicilina não têm efeito contra vírus. Use apenas para infecções bacterianas confirmadas.' },
      { q: 'Posso tomar Amoxicilina com leite?', a: 'Sim, a Amoxicilina pode ser tomada com ou sem alimentos, inclusive com leite, sem perda significativa de eficácia.' },
    ],
  },
  {
    slug: 'losartana-50mg',
    nome: 'Losartana Potássica 50mg',
    principio_ativo: 'Losartana Potássica',
    categoria: 'Anti-hipertensivo',
    classe: 'Antagonista do receptor de angiotensina II (BRA)',
    receita: true,
    tarja: 'Tarja vermelha',
    formas: ['Comprimido revestido'],
    laboratorios: ['EMS', 'Neo Química', 'Medley', 'Merck (Cozaar)'],
    registro_anvisa: true,
    indicacoes: 'A Losartana é indicada para tratamento de hipertensão arterial, nefropatia em pacientes diabéticos tipo 2 com hipertensão e proteinúria, e insuficiência cardíaca quando o paciente não tolera inibidores da ECA.',
    contraindicacoes: 'Contraindicado em gravidez (2º e 3º trimestres), hipersensibilidade à losartana, uso concomitante com alisquireno em diabéticos ou pacientes com insuficiência renal moderada a grave.',
    posologia: {
      adultos: 'Dose inicial usual: 50mg uma vez ao dia. A dose pode ser aumentada para 100mg uma vez ao dia conforme necessidade. Pode ser tomado com ou sem alimentos.',
      criancas: 'Para crianças de 6 a 16 anos com hipertensão: 0,7mg/kg uma vez ao dia (máximo 50mg/dia).',
      idosos: 'Não é necessário ajuste de dose inicial em idosos.',
    },
    composicao: 'Cada comprimido contém: Losartana Potássica 50mg. Excipientes: celulose microcristalina, lactose monoidratada, amido pré-gelatinizado, estearato de magnésio.',
    mecanismo_acao: 'A Losartana bloqueia seletivamente os receptores AT1 de angiotensina II, impedindo a vasoconstrição e a secreção de aldosterona, resultando em redução da pressão arterial.',
    efeitos_adversos: ['Tontura', 'Hipotensão ortostática', 'Hipercalemia', 'Tosse (menos frequente que com inibidores da ECA)', 'Insuficiência renal (em pacientes predispostos)', 'Angioedema (raro)'],
    interacoes: ['AINEs: podem reduzir o efeito anti-hipertensivo', 'Suplementos de potássio: risco de hipercalemia', 'Diuréticos poupadores de potássio: risco de hipercalemia', 'Lítio: pode aumentar os níveis séricos de lítio'],
    conservacao: 'Conservar em temperatura entre 15°C e 30°C, protegido da luz e umidade.',
    superdosagem: 'Em superdosagem, podem ocorrer hipotensão e taquicardia. Procure atendimento médico imediatamente.',
    gravidez: 'Categoria D. Contraindicado no 2º e 3º trimestres. Suspender imediatamente se a paciente engravidar.',
    faq: [
      { q: 'Posso parar de tomar Losartana se minha pressão normalizar?', a: 'Não pare sem orientação médica. A Losartana controla a pressão, mas não cura a hipertensão. Suspender pode causar rebote da pressão arterial.' },
      { q: 'Losartana pode ser tomada à noite?', a: 'Sim, alguns estudos sugerem que tomar anti-hipertensivos à noite pode ser mais eficaz. Converse com seu médico sobre o melhor horário.' },
      { q: 'Losartana engorda?', a: 'A Losartana não está associada ao ganho de peso. Mudanças de peso durante o tratamento geralmente estão relacionadas a outros fatores.' },
      { q: 'Qual a diferença entre Losartana e Enalapril?', a: 'Ambos tratam hipertensão, mas por mecanismos diferentes. A Losartana (BRA) causa menos tosse que o Enalapril (IECA), sendo preferida por pacientes que desenvolvem tosse com IECA.' },
    ],
  },
  {
    slug: 'ibuprofeno-600mg',
    nome: 'Ibuprofeno 600mg',
    principio_ativo: 'Ibuprofeno',
    categoria: 'Anti-inflamatório',
    classe: 'Anti-inflamatório não esteroidal (AINE)',
    receita: false,
    tarja: 'Tarja vermelha',
    formas: ['Comprimido revestido', 'Cápsula', 'Suspensão oral', 'Gel tópico'],
    laboratorios: ['EMS', 'Neo Química', 'Medley', 'Neocraft', 'Abbott (Advil)'],
    registro_anvisa: true,
    indicacoes: 'O Ibuprofeno é indicado para alívio de dores leves a moderadas (dor de cabeça, dor de dente, dor muscular, dor menstrual), febre e processos inflamatórios como artrite reumatoide e osteoartrite.',
    contraindicacoes: 'Contraindicado em úlcera péptica ativa, hipersensibilidade ao ibuprofeno ou outros AINEs, asma associada a AINEs, insuficiência renal ou hepática grave, gravidez no 3º trimestre.',
    posologia: {
      adultos: 'Para dor e febre: 400mg a cada 6 a 8 horas. Para inflamação: 400 a 800mg, 3 a 4 vezes ao dia. Dose máxima: 2.400mg/dia. Sempre tomar com alimentos.',
      criancas: 'Para crianças acima de 6 meses: 5 a 10mg/kg a cada 6 a 8 horas. Dose máxima: 40mg/kg/dia.',
      idosos: 'Usar a menor dose eficaz pelo menor tempo possível. Maior risco de efeitos gastrointestinais e renais.',
    },
    composicao: 'Cada comprimido contém: Ibuprofeno 600mg. Excipientes: celulose microcristalina, amido glicolato de sódio, dióxido de silício, estearato de magnésio, hipromelose.',
    mecanismo_acao: 'O Ibuprofeno inibe de forma não seletiva as enzimas COX-1 e COX-2, reduzindo a síntese de prostaglandinas e tromboxanos, responsáveis pela dor, febre e inflamação.',
    efeitos_adversos: ['Irritação gástrica e úlcera', 'Náusea e vômito', 'Diarreia', 'Tontura', 'Retenção de líquidos', 'Aumento do risco cardiovascular (uso prolongado)', 'Insuficiência renal (uso prolongado)'],
    interacoes: ['Aspirina: aumenta o risco de sangramento gastrointestinal', 'Anticoagulantes: aumenta o risco de sangramento', 'Anti-hipertensivos: pode reduzir o efeito', 'Lítio: pode aumentar os níveis séricos'],
    conservacao: 'Conservar em temperatura abaixo de 30°C, protegido da luz e umidade.',
    superdosagem: 'Em superdosagem, podem ocorrer náusea, vômito, dor abdominal, sonolência e, em casos graves, sangramento gastrointestinal. Procure atendimento médico.',
    gravidez: 'Categoria C (1º e 2º trimestres) e D (3º trimestre). Evitar especialmente no 3º trimestre.',
    faq: [
      { q: 'Ibuprofeno 600mg pode ser partido ao meio?', a: 'Sim, se for comprimido simples. Não parta cápsulas ou comprimidos de liberação prolongada.' },
      { q: 'Posso tomar Ibuprofeno com estômago vazio?', a: 'Não é recomendado. Sempre tome com alimentos, leite ou antiácidos para reduzir o risco de irritação gástrica.' },
      { q: 'Ibuprofeno pode ser tomado junto com Paracetamol?', a: 'Sim, essa combinação é segura e muitas vezes mais eficaz. Os dois têm mecanismos diferentes e não interagem de forma perigosa.' },
      { q: 'Por quanto tempo posso tomar Ibuprofeno?', a: 'Para automedicação, não use por mais de 3 dias para febre ou 5 dias para dor sem orientação médica.' },
    ],
  },
]

export function getBula(slug) {
  return BULAS.find(b => b.slug === slug)
}
